name=RoboCore - TCA9534
version=1.0.0
author=RoboCore Tecnologia (suporte@robocore.net)
maintainer=RoboCore Tecnologia (suporte@robocore.net)
sentence=Library to use the TCA9534 I2C I/O expander.
paragraph=Use the TCA9534 to get more I/O pins with I2C.
category=Signal Input/Output
url=https://github.com/RoboCore/RoboCore_TCA9534
architectures=*
includes=Wire.h,Stream.h
